### ISSUE TITLE
How do we verify certificate chains?

### ISSUE THREAD

**Issue by glasserc** [mozilla-services/poucave#106]
I am comparing the Remote Settings cert verification chain code against Normandy's to try to resolve https://github.com/mozilla/normandy/issues/1890. The Normandy code is quite a bit more complicated than the `x5u`-checking code we have in this repository. In particular, it looks like the Normandy code parses a [series of certificates](https://github.com/mozilla/normandy/blob/master/normandy/recipes/signing.py#L198). I'm not sure how the `cryptography` library works, but it seems like we [only get one cert](https://github.com/mozilla-services/poucave/blob/653c0a6536d2b01ae9b0847b95e1c332b89b6e23/checks/remotesettings/validate_signatures.py#L53). What happens to the rest of the chain?

**Comment by leplatrem** [comment]
We don't verify the whole chain in our Python signature verification code. 

Our code only verifies the signature using the first entry of the chain (leaf?). I could confirm by adding some crap in the cert of the tests, and signature verification passes :)
If I understand this correctly, this means it uses an «intermediate» certificate (the root is the last I imagine). 

According [to the comments here and there](https://stackoverflow.com/a/49282746) verifying using an intermediate certificate (ie. not verifying the whole chain using trusted certificates) is like performing no check at all! 😱 

Seeing the split/parsing code in Normandy does not inspire me much, I would strongly vote for a high-level style, using a library, especially one of reference like `cryptography`.
But `cryptography` does not provide that «chain verification» feature.  There seems to be stuff out there to do it, but no consensus nor official stuff.

@jvehent @g-k could you please help us here? In our context, is it enough to verify that the collection signature and data is valid using the first entry only in the x5u file?

**Comment by g-k** [comment]
> In our context, is it enough to verify that the collection signature and data is valid using the first entry only in the x5u file?

Ideally, we would verify each cert in the chain back to a known trusted root cert like the dev or prod Moz cert hashes that ship with Fx. We do this in the autograph monitor https://github.com/mozilla-services/autograph/blob/master/tools/autograph-monitor/contentsignaturepki.go#L33 against the hardcoded hashes like https://github.com/mozilla-services/autograph/blob/cddc4b07e200dd080f0125b4e2006ebce20d127f/tools/autograph-monitor/xpi.go#L22

We could probably hardcode the intermediate and verify against that too, but since it sounds like we'd need to build out the chain verification feature (at least for 3 cert chains) we might as well verify against the root.

There's an upstream issue in `cryptography` for chain validation, but it might be considered out of scope. There are a few links to other libraries that implement the feature at https://github.com/pyca/cryptography/issues/2381#issuecomment-415958399

Regardless, it'd be useful to wrap up the feature in a library for other python services using content signature to reuse (cc @jvehent re: finding time to build or help build that library).
