### ISSUE TITLE
Take sampling into account in Uptake Telemetry

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/poucave#351]
* Uptake events are sampled at 1% on release and ers
* Currently, when we compute error rates, we don't take sampling into account.

For example, if we receive:
- 1 error on nightly
- 1 error on release
- 8 success on release
Error rate is 20%

While the effective error rate is 11%. (1 + 100 / 1 + 100 + 800)

**Comment by leplatrem** [comment]
The query could look like this:
```sql
WITH uptake_telemetry AS (
    ...
),
expended_totals AS (
    SELECT
        min_timestamp,
        max_timestamp,
        source,
        status,
        version,
        (CASE WHEN normalized_channel = 'release' OR normalized_channel = 'esr' THEN COUNT(*) * 100 ELSE COUNT(*) END) AS total
    FROM uptake_telemetry
    GROUP BY period, source, status, version, normalized_channel
)
SELECT
    min_timestamp,
    max_timestamp,
    source,
    status,
    version,
    SUM(total) AS total
FROM expended_totals
GROUP BY period, source, status, version
ORDER BY period, source
```

**Comment by leplatrem** [comment]
Not taking sampling into account has the advantage of emphasizing issues on nightly and beta.

For example, investigating `sync_error` issues, first without multiplying esr/release, then taking sampling into account:

![Screenshot from 2020-02-21 10-43-28](https://user-images.githubusercontent.com/546692/75022832-10fc8180-5497-11ea-84c4-1f9e7b30e2c8.png)

![Screenshot from 2020-02-21 10-41-33](https://user-images.githubusercontent.com/546692/75022834-11951800-5497-11ea-9bce-7d940eec4f6a.png)

([source](https://sql.telemetry.mozilla.org/queries/67923/))

@mythmon @glasserc What do you think?

**Comment by glasserc** [comment]
I'm of two minds about this. While there are numerically more errors on release, and the majority of our users on release, we have much more control over nightly and beta and I think we should prioritize those numbers as early warnings. I think I have a slight preference for the way things are?

**Comment by mythmon** [comment]
I think that looking at the _number_ of errors isn't enough. I think that what we care about is the _rate_ of errors. If these were normalized to the number of clients on the channel, or the number of successes, I think the numbers would be more meaningful. Then it wouldn't really matter if we are sampling or not, because we would presumably be sampling the numerator and denominator the same way.

Aside from that, I also think that for some types of errors, Release is more useful than Nightly. Specifically, most work done with Normandy is done only on Release, and rarely on Nightly. I realize that Normandy is not the only use case. It seems that which channel we pay attention to depends on what kind of errors we care about.

Finally, does it even make sense to include these in the same check? Or would it make more sense to split them out by channel? I feel like the first thing I'm going to ask if I get an error report from this is which channel it is coming from. Right now, since 73 is the current version of Release, errors being reported from 73 Release matter a lot more than errors being reported from 73 Nightly.

**Comment by leplatrem** [comment]
Done in v1.18, uptake can be split into channels :) Thanks everyone for your feedback!
