### ISSUE TITLE
Add an initial check for the Data Platform

### ISSUE THREAD

**Issue by mreid-moz** [mozilla-services/poucave#388]
My team is interested in trying out poucave for monitoring the status of the data platform.

Is it OK for us to contribute new checks here? Can they be run via the already-deployed service?

**Comment by mreid-moz** [comment]
cc @mostlygeek

**Comment by leplatrem** [comment]
Your checks are welcomed here yes! Just add a new module in the `checks/` folder :) 

However, I'd recommend running a poucave instance of your own, because in the current UI all checks are shown together

**Comment by mostlygeek** [comment]
To start with can we have all the checks together?  On our SVG it'll be great to turn the "telemetry" block into more specific checks

**Comment by Ben-Wu** [comment]
Is it possible for us to modify the deployed config files?  Where are those located?

**Comment by leplatrem** [comment]
> To start with can we have all the checks together? On our SVG it'll be great to turn the "telemetry" block into more specific checks

Okay, I guess it's a matter of granularity and amount of new checks.

Since poucave has no backend I'd have thought that spinning and running new instances would be cheap. And if the checks are in the same repo, we can run some of the Telemetry checks in our instance (and vice-versa).

If we choose to run all the checks in the same instance, unless there are only a few of them, I guess we would have to add some filtering feature on the UI (by tag for example).

> Is it possible for us to modify the deployed config files? Where are those located?

Config is here:
https://github.com/mozilla-services/cloudops-infra/blob/master/projects/poucave/k8s/charts/poucave/configs/poucave/config.toml.tpl

**Comment by Ben-Wu** [comment]
We'll probably only have a couple simple checks to start off to try this out.  If we want to expand on this later then ui filtering or running a separate instance would be the way to go.
